import type { DataEngineCatalogEntry, DataEngineCatalogResponse } from "../../../common/types/index.js";

const ENGINE_CATALOG: DataEngineCatalogEntry[] = [
  {
    key: "customer-daily-consumption",
    name: "Customer Daily Consumption Engine",
    category: "consumption",
    status: "implemented",
    endpointNames: [
      "/api/customer/consumption-recharge-summary",
      "/api/customer/consumption-recharge-daily",
      "/api/customer/live-daily-consumption",
      "/api/customer/segments",
      "/api/customer/forecasts",
    ],
    inputApis: [
      "/api/DailyDataMeter/read",
      "/api/DailyDataMeter/readHourly",
      "/api/customer/read",
      "/api/account/read",
      "/api/meter/read",
    ],
    formulas: [
      "daily_consumption_kwh = SUM(consumption_kwh by meter and reading_date)",
      "customer_daily_consumption = SUM(mapped meter daily consumption)",
      "today_live_delta = latest_today_value - last_saved_today_value",
    ],
    supabaseTables: [
      "meter_daily_reads",
      "customer_daily_recharge_facts",
      "customer_daily_consumption_facts",
      "customer_segments",
      "customer_forecasts",
    ],
    refreshInterval: "Today every 60 seconds via hourly overlay, history every few minutes or nightly",
    workerSchedule: "Dedicated customer-daily worker every 60s",
    backendServices: ["customer-analytics", "customer-fact-engine", "supabase-db"],
    frontendPages: ["/management/customer", "/data-report/consumption-statistics", "/dashboard"],
  },
  {
    key: "recharge-ingestion",
    name: "Recharge Ingestion Engine",
    category: "revenue",
    status: "partial",
    endpointNames: ["/api/token/creditTokenRecord/readMore", "/api/customer/consumption-recharge-summary"],
    inputApis: ["/api/token/creditTokenRecord/readMore", "/api/customer/read", "/api/account/read"],
    formulas: [
      "daily_recharge_amount = SUM(amount)",
      "daily_recharge_kwh = SUM(kwh)",
      "customer_recharge_count = COUNT(transactions)",
    ],
    supabaseTables: ["token_transactions", "customers", "accounts"],
    refreshInterval: "Every 5 minutes",
    workerSchedule: "Token analytics snapshot cache every 5 minutes",
    backendServices: ["management-token-analytics", "supabase-db"],
    frontendPages: ["/token-record/credit-token-record", "/management/customer", "/management/analytics", "/dashboard"],
  },
  {
    key: "sold-vs-consumed",
    name: "Sold vs Consumed Reconciliation Engine",
    category: "warehouse",
    status: "implemented",
    endpointNames: ["/api/token/reconciliation"],
    inputApis: ["/api/token/creditTokenRecord/readMore", "/API/LoadProfile/DailyData", "/api/tariff/read"],
    formulas: [
      "variance_kwh = consumed_kwh - sold_kwh",
      "variance_pct = ((consumed_kwh - sold_kwh) / sold_kwh) * 100",
      "yield_ngn_per_kwh = recharge_amount / sold_kwh",
    ],
    supabaseTables: ["token_transactions", "meter_daily_reads"],
    refreshInterval: "Every 5 minutes for today, nightly for backfill",
    workerSchedule: "Read-on-demand with cached token snapshot",
    backendServices: ["analytics-mix", "management-token-analytics"],
    frontendPages: ["/token-record/credit-token-record", "/data-report/consumption-statistics", "/management/customer"],
  },
  {
    key: "customer-360",
    name: "Customer 360 Engine",
    category: "operations",
    status: "implemented",
    endpointNames: ["/api/customer/360-lite"],
    inputApis: ["/api/customer/read", "/api/account/read", "/api/meter/read", "/api/token/creditTokenRecord/readMore"],
    formulas: [
      "last_recharge_at = MAX(transaction_at)",
      "total_recharge_90d = SUM(last 90d amount)",
      "recharge_count_90d = COUNT(last 90d transactions)",
    ],
    supabaseTables: ["customers", "accounts", "meters", "token_transactions"],
    refreshInterval: "Every 10 minutes",
    workerSchedule: "Snapshot/cache refresh every 10 minutes",
    backendServices: ["analytics-mix", "management-token-analytics"],
    frontendPages: ["/management/customer", "/management/account", "/management/meter"],
  },
  {
    key: "runtime-freshness",
    name: "Runtime Freshness Engine",
    category: "monitoring",
    status: "implemented",
    endpointNames: ["/api/runtime/engines", "/health", "/health/dependencies"],
    inputApis: ["/api/runtime/engines", "/health", "/health/dependencies"],
    formulas: [
      "dataset_age_minutes = now - last_updated_at",
      "freshness_score = 100 - stale penalties",
      "engine_health = healthy/warning/critical",
    ],
    supabaseTables: ["runtime_health_facts"],
    refreshInterval: "Every 1 minute",
    workerSchedule: "Runtime poll every 60 seconds",
    backendServices: ["runtime", "runtime-diagnostics"],
    frontendPages: ["/system/runtime", "/dashboard"],
  },
  {
    key: "revenue-leakage",
    name: "Revenue Leakage Engine",
    category: "risk",
    status: "implemented",
    endpointNames: ["/api/dashboard/risk-overlay", "/api/runtime/revenue-leakage"],
    inputApis: ["/api/reports/low-purchase", "/api/reports/non-purchase", "/api/theft/signals/read"],
    formulas: [
      "leakage_score = low_purchase_weight + nonpurchase_weight + theft_weight + variance_weight",
      "estimated_loss = missing_kwh * tariff_rate",
    ],
    supabaseTables: ["revenue_leakage_facts", "theft_signals", "token_transactions", "meter_daily_reads"],
    refreshInterval: "Every 15 minutes",
    workerSchedule: "Risk worker every 15 minutes",
    backendServices: ["analysis-engine", "theft-intelligence", "priority-engines"],
    frontendPages: ["/dashboard", "/data-report/low-purchase", "/data-report/long-nonpurchase", "/data-report/theft-signals"],
  },
  {
    key: "collections-priority",
    name: "Collections Priority Engine",
    category: "risk",
    status: "implemented",
    endpointNames: ["/api/reports/collections-priority"],
    inputApis: ["/api/reports/low-purchase", "/api/reports/non-purchase", "/api/theft/cases/read"],
    formulas: [
      "priority = low_balance_score + nonpurchase_score + open_case_score + recharge_drop_score",
      "days_since_last_recharge = today - MAX(transaction_at)",
    ],
    supabaseTables: ["collections_priority_facts", "token_transactions", "theft_cases"],
    refreshInterval: "Every 15 minutes",
    workerSchedule: "Read-on-demand with cached risk state",
    backendServices: ["analytics-mix", "theft-intelligence"],
    frontendPages: ["/data-report/low-purchase", "/data-report/long-nonpurchase", "/management/customer"],
  },
  {
    key: "meter-health",
    name: "Meter Health Engine",
    category: "monitoring",
    status: "implemented",
    endpointNames: ["/api/meter/performance-sheet"],
    inputApis: ["/api/meter/read", "/api/gateway/read", "/api/DailyDataMeter/read", "/api/dlms/Read"],
    formulas: [
      "read_age_hours = now - last_read_at",
      "health_score = 100 - stale penalty - missing gateway penalty - missing protocol penalty",
    ],
    supabaseTables: ["meters", "meter_daily_reads"],
    refreshInterval: "Every 5 minutes",
    workerSchedule: "Read-on-demand",
    backendServices: ["analytics-mix"],
    frontendPages: ["/management/meter", "/dashboard", "/remote-operation/meter-reading"],
  },
  {
    key: "notification-correlation",
    name: "Notification Correlation Engine",
    category: "monitoring",
    status: "implemented",
    endpointNames: ["/api/notifications/correlated-feed"],
    inputApis: ["/api/notifications", "/api/theft/signals/read", "/api/dashboard"],
    formulas: [
      "severity = max(notification severity, linked theft severity, alarm pressure)",
      "linked_risk_score = theft_score when meter matches",
    ],
    supabaseTables: ["notifications", "notification_receipts", "theft_signals"],
    refreshInterval: "Every 1 minute",
    workerSchedule: "Notification poll every 60 seconds",
    backendServices: ["analysis-engine", "theft-intelligence", "analytics-mix"],
    frontendPages: ["/dashboard", "/event-notification"],
  },
  {
    key: "master-data-consistency",
    name: "Master Data Consistency Engine",
    category: "warehouse",
    status: "implemented",
    endpointNames: ["/api/master-data/consistency"],
    inputApis: ["/api/customer/read", "/api/account/read", "/api/meter/read", "/api/gateway/read", "/api/tariff/read"],
    formulas: [
      "quality_score = 100 - 20 * missing_relations",
      "flags = missing customer/account/gateway/tariff",
    ],
    supabaseTables: ["customers", "accounts", "meters"],
    refreshInterval: "Every 6 hours",
    workerSchedule: "Master-data quality scan every 6 hours",
    backendServices: ["analytics-mix"],
    frontendPages: ["/management/customer", "/management/account", "/management/meter", "/management/gateway", "/management/tariff"],
  },
  {
    key: "site-benchmark",
    name: "Site Benchmark Engine",
    category: "consumption",
    status: "implemented",
    endpointNames: ["/api/management/analytics/site-benchmark", "/api/site-consumption/loss-exposure"],
    inputApis: ["/api/site-consumption/report", "/api/management/analytics/consumption", "/api/meters/stats/sites"],
    formulas: [
      "site_revenue = SUM(recharge_amount)",
      "site_kwh = SUM(consumption_kwh)",
      "share_pct = site_kwh / portfolio_kwh * 100",
      "yield = site_revenue / site_kwh",
    ],
    supabaseTables: ["site_consumption_facts", "token_transactions"],
    refreshInterval: "Every 15 minutes",
    workerSchedule: "Site consumption engine every 30 minutes, query cache every 15 minutes",
    backendServices: ["site-consumption-engine", "analytics-mix", "management-token-analytics"],
    frontendPages: ["/management/analytics", "/data-report/site-consumption", "/dashboard"],
  },
  {
    key: "customer-segmentation",
    name: "Customer Segmentation Engine",
    category: "forecasting",
    status: "implemented",
    endpointNames: ["/api/customer/segments"],
    inputApis: ["/api/customer/read", "/api/token/creditTokenRecord/readMore", "/api/DailyDataMeter/read"],
    formulas: [
      "segment by recharge frequency, average vend size, monthly consumption, and risk score",
    ],
    supabaseTables: ["customer_segments", "token_transactions", "meter_daily_reads", "customers"],
    refreshInterval: "Nightly",
    workerSchedule: "Nightly segmentation worker",
    backendServices: ["customer-analytics", "customer-fact-engine"],
    frontendPages: ["/management/customer", "/management/analytics"],
  },
  {
    key: "depletion-forecast",
    name: "Demand / Depletion Forecast Engine",
    category: "forecasting",
    status: "implemented",
    endpointNames: ["/api/customer/forecasts"],
    inputApis: ["/api/DailyDataMeter/read", "/api/reports/low-purchase", "/api/token/creditTokenRecord/readMore"],
    formulas: [
      "avg_daily_use_7d = SUM(last 7d consumption)/7",
      "days_to_zero = current_balance / avg_daily_use_7d",
      "next_recharge_prediction = last_recharge_pattern + avg_cycle_length",
    ],
    supabaseTables: ["customer_forecasts", "meter_daily_reads", "token_transactions"],
    refreshInterval: "Every 15 minutes for active customers, nightly full recompute",
    workerSchedule: "Forecast worker every 15 minutes plus nightly rebuild",
    backendServices: ["customer-analytics", "customer-fact-engine"],
    frontendPages: ["/data-report/low-purchase", "/management/customer", "/dashboard"],
  },
  {
    key: "operational-priority",
    name: "Operational Priority Engine",
    category: "operations",
    status: "implemented",
    endpointNames: ["/api/runtime/operational-priority"],
    inputApis: ["/api/theft/prioritization", "/api/reports/collections-priority", "/api/meter/performance-sheet", "/api/runtime/engines"],
    formulas: [
      "priority_score = business_value + risk + staleness + outage_impact",
      "queue_rank = sort(priority_score desc)",
    ],
    supabaseTables: ["operational_priority_queue", "runtime_health_facts"],
    refreshInterval: "Every 5 minutes",
    workerSchedule: "Operations worker every 5 minutes",
    backendServices: ["priority-engines", "runtime"],
    frontendPages: ["/dashboard", "/system/runtime", "/management/analytics"],
  },
  {
    key: "wallet-reconciliation",
    name: "Wallet Reconciliation Engine",
    category: "operations",
    status: "implemented",
    endpointNames: ["/api/reconciliation/run", "/api/reconciliation/summary", "/api/reconciliation/exceptions"],
    inputApis: ["/api/runtime/engines", "/api/wallet/overview", "/api/wallet/history"],
    formulas: [
      "L1 = ledger vs snapshot balance drift check",
      "L2 = purchase reservation ageing and upstream mismatch checks",
      "L3-L5 = funding, commission, and settlement reconciliation checks",
    ],
    supabaseTables: [
      "wallet_reconciliation_runs",
      "wallet_exceptions",
      "wallet_settlement_batches",
      "ledger_journals",
    ],
    refreshInterval: "Every 10 minutes",
    workerSchedule: "Wallet reconciliation scheduler every 10 minutes",
    backendServices: ["wallet-reconciliation", "wallet-reconciliation-engine", "wallet-settlement"],
    frontendPages: ["/management/reconciliation", "/management/exceptions", "/management/settlement", "/system/runtime"],
  },
];

export function readDataEngineCatalog(): DataEngineCatalogResponse {
  return {
    generatedAt: new Date().toISOString(),
    entries: ENGINE_CATALOG,
  };
}
