import type { AppPageConfig } from "../types/index.ts";
import {
  accountColumns,
  accountManagementFields,
  createClientExportAction,
  createManagementPage,
  customerColumns,
  customerManagementFields,
  dateRangeFilters,
  eventNotificationColumns,
  gatewayColumns,
  gatewayManagementFields,
  logColumns,
  meterColumns,
  meterManagementFields,
  searchFilter,
  tariffColumns,
  tariffManagementFields,
} from "./page-catalog-shared.ts";

export const managementPages: AppPageConfig[] = [
  {
    kind: "dashboard",
    path: "/management/analytics",
    title: "Management Analytics",
    menuLabel: "Analytics",
    description: "Robust data trends and site-wide energy consumption analysis.",
    sectionKey: "management",
  },
  createManagementPage(
    "/management/customer",
    "Customer Management",
    "Customer",
    "/api/customer/read",
    customerColumns,
    {
      formFields: customerManagementFields,
    },
  ),
  createManagementPage(
    "/management/account",
    "Account Management",
    "Account",
    "/api/account/read",
    accountColumns,
    {
      formFields: accountManagementFields,
    },
  ),
  createManagementPage(
    "/management/tariff",
    "Tariff Management",
    "Tariff",
    "/api/tariff/read",
    tariffColumns,
    {
      formFields: tariffManagementFields,
    },
  ),
  createManagementPage(
    "/management/gateway",
    "Gateway Management",
    "Gateway",
    "/api/gateway/read",
    gatewayColumns,
    {
      formFields: gatewayManagementFields,
    },
  ),
  createManagementPage(
    "/management/meter",
    "Meter Management",
    "Meter",
    "/api/meter/read",
    meterColumns,
    {
      formFields: meterManagementFields,
      sectionKey: "meter",
    },
  ),

  {
    kind: "data",
    path: "/event-notification",
    title: "Event Notification",
    menuLabel: "Event Notification",
    description: "Upstream event notification feed from meters and gateways.",
    sectionKey: "event",
    readEndpoint: "/API/EventNotification/Read",
    readOperationKind: "table-read",
    filters: [searchFilter, ...dateRangeFilters],
    columns: eventNotificationColumns,
    toolbarActions: [createClientExportAction("/API/EventNotification/Read")],
    live: { enabled: true, intervalMs: 10_000, pauseOnHidden: true, critical: true },
    riskIntegration: {
      canOpenCase: true,
      riskSignals: ["tamper-event", "relay-event", "event-correlation"],
    },
    requiredPermissions: [
      "EventNotification.EventNotification",
      "EventNotification.Read",
      "EventNotification",
    ],
  },
  {
    kind: "data",
    path: "/system-log",
    title: "System Log",
    menuLabel: "System Log",
    description: "Audit trail and system activity log viewer.",
    sectionKey: "log",
    readEndpoint: "/api/Log/read",
    readOperationKind: "table-read",
    filters: [searchFilter, ...dateRangeFilters],
    columns: logColumns,
    toolbarActions: [createClientExportAction("/api/Log/read")],
    live: { enabled: true, intervalMs: 12_000, pauseOnHidden: true, critical: true },
    riskIntegration: {
      canOpenCase: true,
      riskSignals: ["audit-anomaly", "suspicious-ops"],
    },
    requiredRole: "admin",
    requiredPermissions: [
      "SystemLog.SystemLog",
      "SystemLog.Read",
      "Log.SystemLog",
      "Log.Log",
    ],
  },
  {
    kind: "profile",
    path: "/profile",
    title: "Profile",
    menuLabel: "Profile",
    description: "Modify account information, login password, and authorization password.",
    sectionKey: "management",
    includeInNavigation: false,
  },
  {
    kind: "runtime-admin",
    path: "/system/runtime",
    title: "Runtime Operations",
    menuLabel: "Runtime Ops",
    description: "Operational controls for background engines and scheduler leadership.",
    sectionKey: "runtime-ops",
    requiredRole: "admin",
  },

];
