import type { AppPageConfig } from "../types/index.ts";
import {
  accountColumns,
  accountManagementFields,
  createClientExportAction,
  createManagementPage,
  customerColumns,
  customerManagementFields,
  dateRangeFilters,
  debtColumns,
  debtManagementFields,
  eventNotificationColumns,
  gatewayColumns,
  gatewayManagementFields,
  logColumns,
  meterColumns,
  meterManagementFields,
  roleColumns,
  roleManagementFields,
  searchFilter,
  stationColumns,
  stationManagementFields,
  tariffColumns,
  tariffManagementFields,
  userAdminColumns,
  userAdminFields,
} from "./page-catalog-shared.ts";

export const managementPages: AppPageConfig[] = [
  {
    kind: "dashboard",
    path: "/management/analytics",
    title: "Management Analytics",
    menuLabel: "Analytics",
    description: "Robust data trends and site-wide energy consumption analysis.",
    sectionKey: "management",
    includeInNavigation: false,
  },
  createManagementPage(
    "/management/station",
    "Station Management",
    "Station",
    "/api/station/read",
    stationColumns,
    {
      formFields: stationManagementFields,
    },
  ),
  createManagementPage(
    "/management/customer",
    "Customer Management",
    "Customer",
    "/api/customer/read",
    customerColumns,
    {
      formFields: customerManagementFields,
    },
  ),
  createManagementPage(
    "/management/account",
    "Account Management",
    "Account",
    "/api/account/read",
    accountColumns,
    {
      formFields: accountManagementFields,
    },
  ),
  createManagementPage(
    "/management/tariff",
    "Tariff Management",
    "Tariff",
    "/api/tariff/read",
    tariffColumns,
    {
      formFields: tariffManagementFields,
    },
  ),
  createManagementPage(
    "/management/debt",
    "Debt Management",
    "Debt",
    "/api/debt/read",
    debtColumns,
    {
      formFields: debtManagementFields,
    },
  ),
  createManagementPage(
    "/management/role",
    "Role Management",
    "Role",
    "/api/role/read",
    roleColumns,
    {
      formFields: roleManagementFields,
    },
  ),
  createManagementPage(
    "/management/gateway",
    "Gateway Management",
    "Gateway",
    "/api/gateway/read",
    gatewayColumns,
    {
      formFields: gatewayManagementFields,
    },
  ),
  createManagementPage(
    "/management/meter",
    "Meter Management",
    "Meter",
    "/api/meter/read",
    meterColumns,
    {
      formFields: meterManagementFields,
    },
  ),
  createManagementPage(
    "/management/user-admin",
    "User Management",
    "User",
    "/api/user/read",
    userAdminColumns,
    {
      formFields: userAdminFields,
    },
  ),
  {
    kind: "data",
    path: "/event-notification",
    title: "Event Notification",
    menuLabel: "Event Notification",
    description: "Upstream event notification feed from meters and gateways.",
    sectionKey: "event",
    readEndpoint: "/API/EventNotification/Read",
    readOperationKind: "table-read",
    filters: [searchFilter, ...dateRangeFilters],
    columns: eventNotificationColumns,
    toolbarActions: [createClientExportAction("/API/EventNotification/Read")],
    live: { enabled: true, intervalMs: 10_000, pauseOnHidden: true, critical: true },
    riskIntegration: {
      canOpenCase: true,
      riskSignals: ["tamper-event", "relay-event", "event-correlation"],
    },
    requiredPermissions: [
      "EventNotification.EventNotification",
      "EventNotification.Read",
      "EventNotification",
    ],
  },
  {
    kind: "data",
    path: "/system-log",
    title: "System Log",
    menuLabel: "System Log",
    description: "Audit trail and system activity log viewer.",
    sectionKey: "log",
    readEndpoint: "/api/Log/read",
    readOperationKind: "table-read",
    filters: [searchFilter, ...dateRangeFilters],
    columns: logColumns,
    toolbarActions: [createClientExportAction("/api/Log/read")],
    live: { enabled: true, intervalMs: 12_000, pauseOnHidden: true, critical: true },
    riskIntegration: {
      canOpenCase: true,
      riskSignals: ["audit-anomaly", "suspicious-ops"],
    },
    requiredRole: "admin",
    requiredPermissions: [
      "SystemLog.SystemLog",
      "SystemLog.Read",
      "Log.SystemLog",
      "Log.Log",
    ],
  },
  {
    kind: "profile",
    path: "/profile",
    title: "Profile",
    menuLabel: "Profile",
    description: "Modify account information, login password, and authorization password.",
    sectionKey: "management",
    includeInNavigation: false,
  },
];
