import type { AppPageConfig } from "../types/index.ts";
import {
  accountColumns,
  accountManagementFields,
  createClientExportAction,
  createManagementPage,
  customerColumns,
  customerManagementFields,
  dateRangeFilters,
  debtColumns,
  debtManagementFields,
  dlmsColumns,
  dlmsManagementFields,
  dlt645Columns,
  dlt645ManagementFields,
  dlt645TaskColumns,
  eventNotificationColumns,
  gatewayColumns,
  gatewayManagementFields,
  itemColumns,
  itemManagementFields,
  logColumns,
  meterColumns,
  meterManagementFields,
  searchFilter,
  tariffColumns,
  tariffManagementFields,
} from "./page-catalog-shared.ts";

export const managementPages: AppPageConfig[] = [
  createManagementPage(
    "/management/customer",
    "Customer Management",
    "Customer",
    "/api/customer/read",
    customerColumns,
    { formFields: customerManagementFields },
  ),
  createManagementPage(
    "/management/account",
    "Account Management",
    "Account",
    "/api/account/read",
    accountColumns,
    { formFields: accountManagementFields },
  ),
  createManagementPage(
    "/management/tariff",
    "Tariff Management",
    "Tariff",
    "/api/tariff/read",
    tariffColumns,
    { formFields: tariffManagementFields },
  ),
  createManagementPage(
    "/management/gateway",
    "Gateway Management",
    "Gateway",
    "/api/gateway/read",
    gatewayColumns,
    { formFields: gatewayManagementFields },
  ),
  createManagementPage(
    "/management/meter",
    "Meter Management",
    "Meter",
    "/api/meter/read",
    meterColumns,
    { formFields: meterManagementFields, sectionKey: "meter" },
  ),
  createManagementPage(
    "/management/debt",
    "Debt Management",
    "Debt",
    "/api/debt/read",
    debtColumns,
    { formFields: debtManagementFields, sectionKey: "debt" },
  ),
  createManagementPage(
    "/management/item",
    "Item Management",
    "Item",
    "/api/item/read",
    itemColumns,
    { formFields: itemManagementFields },
  ),
  createManagementPage(
    "/protocol/dlms",
    "DLMS Management",
    "DLMS",
    "/api/dlms/Read",
    dlmsColumns,
    { formFields: dlmsManagementFields, sectionKey: "protocol" },
  ),
  createManagementPage(
    "/protocol/dlt645",
    "DLT645 Management",
    "DLT645",
    "/api/dlt645/read",
    dlt645Columns,
    { formFields: dlt645ManagementFields, sectionKey: "protocol" },
  ),
  {
    kind: "data",
    path: "/protocol/dlt645-task",
    title: "DLT645 Task",
    menuLabel: "DLT645 Task",
    description: "Read-only view of DLT645 protocol task history.",
    sectionKey: "protocol",
    readEndpoint: "/api/DLT645Task/read",
    readOperationKind: "task-read",
    filters: [searchFilter],
    columns: dlt645TaskColumns,
    toolbarActions: [createClientExportAction("/api/DLT645Task/read")],
  },
  {
    kind: "data",
    path: "/event-notification",
    title: "Event Notification",
    menuLabel: "Event Notification",
    description: "Upstream event notification feed from meters and gateways.",
    sectionKey: "event",
    readEndpoint: "/API/EventNotification/Read",
    readOperationKind: "table-read",
    filters: [searchFilter, ...dateRangeFilters],
    columns: eventNotificationColumns,
    toolbarActions: [createClientExportAction("/API/EventNotification/Read")],
    requiredPermissions: [
      "EventNotification.EventNotification",
      "EventNotification.Read",
      "EventNotification",
    ],
  },
  {
    kind: "data",
    path: "/system-log",
    title: "System Log",
    menuLabel: "System Log",
    description: "Audit trail and system activity log viewer.",
    sectionKey: "log",
    readEndpoint: "/api/Log/read",
    readOperationKind: "table-read",
    filters: [searchFilter, ...dateRangeFilters],
    columns: logColumns,
    toolbarActions: [createClientExportAction("/api/Log/read")],
    requiredRole: "admin",
    requiredPermissions: [
      "SystemLog.SystemLog",
      "SystemLog.Read",
      "Log.SystemLog",
      "Log.Log",
    ],
  },
  {
    kind: "profile",
    path: "/profile",
    title: "Profile",
    menuLabel: "Profile",
    description: "Modify account information, login password, and authorization password.",
    sectionKey: "management",
    includeInNavigation: false,
  },
  {
    kind: "runtime-admin",
    path: "/system/runtime",
    title: "Runtime Operations",
    menuLabel: "Runtime Ops",
    description: "Operational controls for background engines and scheduler leadership.",
    sectionKey: "log",
    requiredRole: "admin",
  },
];
