import type { AppPageConfig } from "../types/index.ts";
import {
  controlTaskFields,
  createReadOnlyTaskPage,
  createRemoteOperationPage,
  field,
  genericTaskColumns,
  meterControlTaskColumns,
  meterReadingTaskColumns,
  meterTokenTaskColumns,
  readingTaskFields,
  searchFilter,
  settingTaskFields,
  tokenTaskFields,
  transparentForwardingFields,
} from "./page-catalog-shared.ts";

export const remotePages: AppPageConfig[] = [
  createRemoteOperationPage(
    "/remote-operation/meter-reading",
    "Meter Reading",
    "Meter Reading",
    "/API/RemoteMeterTask/CreateReadingTask",
    {
      remoteTaskType: "reading",
      payloadBuilderKey: "reading",
      fields: readingTaskFields,
      dangerLevel: "low",
      successRedirectPath: "/remote-operation-task/meter-reading-task",
    },
  ),
  createRemoteOperationPage(
    "/remote-operation/meter-setting",
    "Meter Setting",
    "Meter Setting",
    "/API/RemoteMeterTask/CreateSettingTask",
    {
      remoteTaskType: "setting",
      payloadBuilderKey: "setting",
      fields: settingTaskFields,
      dangerLevel: "medium",
      requiresReviewStep: true,
      confirmMessage: "Review this meter setting command before sending it upstream.",
      successRedirectPath: "/remote-operation-task/meter-setting-task",
    },
  ),
  createRemoteOperationPage(
    "/remote-operation/meter-control",
    "Meter Control",
    "Meter Control",
    "/API/RemoteMeterTask/CreateControlTask",
    {
      remoteTaskType: "control",
      payloadBuilderKey: "control",
      fields: controlTaskFields,
      dangerLevel: "high",
      requiresReviewStep: true,
      confirmMessage: "This command can change live meter state. Confirm the target and action before submit.",
      successRedirectPath: "/remote-operation-task/meter-control-task",
    },
  ),
  createRemoteOperationPage(
    "/remote-operation/meter-token",
    "Meter Token",
    "Meter Token",
    "/API/RemoteMeterTask/CreateTokenTask",
    {
      remoteTaskType: "token",
      payloadBuilderKey: "token",
      fields: tokenTaskFields,
      dangerLevel: "high",
      requiresReviewStep: true,
      confirmMessage: "This command sends a remote token operation. Confirm the target and token type before submit.",
      successRedirectPath: "/remote-operation-task/meter-token-task",
    },
  ),
  createRemoteOperationPage(
    "/remote-operation/transparent-forwarding",
    "Transparent Forwarding",
    "Transparent Forwarding",
    "/API/RemoteMeterTask/CreateTransparentForwardingTask",
    {
      remoteTaskType: "transparent-forwarding",
      payloadBuilderKey: "transparent-forwarding",
      fields: transparentForwardingFields,
      dangerLevel: "high",
      requiresReviewStep: true,
      confirmMessage: "Transparent forwarding sends a raw meter command. Confirm the payload and target carefully before submit.",
      successRedirectPath: "/remote-operation-task/transparent-forwarding-task",
    },
  ),
  createReadOnlyTaskPage(
    "/remote-operation-task/meter-reading-task",
    "Meter Reading Task",
    "Meter Reading Task",
    "/API/RemoteMeterTask/GetReadingTask",
    {
      columns: meterReadingTaskColumns,
      filters: [searchFilter],
      rowActions: [
        {
          key: "retry-reading",
          label: "Retry",
          endpoint: "/API/RemoteMeterTask/UpdateReadingTask",
          operationKind: "task-update",
          tone: "primary",
          fields: [field("remark", "Remark", "Optional retry note")],
          confirmMessage: "Retry this reading task?",
        },
      ],
    },
  ),
  createReadOnlyTaskPage(
    "/remote-operation-task/meter-setting-task",
    "Meter Setting Task",
    "Meter Setting Task",
    "/API/RemoteMeterTask/GetSettingTask",
    {
      columns: genericTaskColumns,
      filters: [searchFilter],
      rowActions: [
        {
          key: "retry-setting",
          label: "Retry",
          endpoint: "/API/RemoteMeterTask/UpdateSettingTask",
          operationKind: "task-update",
          tone: "primary",
          fields: [field("remark", "Remark", "Optional retry note")],
          confirmMessage: "Retry this setting task?",
        },
      ],
    },
  ),
  createReadOnlyTaskPage(
    "/remote-operation-task/meter-control-task",
    "Meter Control Task",
    "Meter Control Task",
    "/API/RemoteMeterTask/GetControlTask",
    {
      columns: meterControlTaskColumns,
      filters: [searchFilter],
      rowActions: [
        {
          key: "retry-control",
          label: "Retry",
          endpoint: "/API/RemoteMeterTask/UpdateControlTask",
          operationKind: "task-update",
          tone: "danger",
          fields: [field("remark", "Remark", "Optional retry note")],
          confirmMessage: "Retry this control task?",
        },
      ],
    },
  ),
  createReadOnlyTaskPage(
    "/remote-operation-task/meter-token-task",
    "Meter Token Task",
    "Meter Token Task",
    "/API/RemoteMeterTask/GetTokenTask",
    {
      columns: meterTokenTaskColumns,
      filters: [searchFilter],
      rowActions: [
        {
          key: "retry-token",
          label: "Retry",
          endpoint: "/API/RemoteMeterTask/UpdateTokenTask",
          operationKind: "task-update",
          tone: "danger",
          fields: [field("remark", "Remark", "Optional retry note")],
          confirmMessage: "Retry this token task?",
        },
      ],
    },
  ),
  createReadOnlyTaskPage(
    "/remote-operation-task/transparent-forwarding-task",
    "Transparent Forwarding Task",
    "Transparent Forwarding Task",
    "/API/RemoteMeterTask/GetTransparentForwardingTask",
    { columns: genericTaskColumns, filters: [searchFilter] },
  ),
];
