import type { AppPageConfig } from "../types/index.ts";
import {
  createClientExportAction,
  dateRangeFilters,
  filterField,
  intervalColumns,
  loadProfileColumns,
  searchFilter,
} from "./page-catalog-shared.ts";

export const reportPages: AppPageConfig[] = [
  {
    kind: "data",
    path: "/data-report/long-nonpurchase",
    title: "Long Nonpurchase Situation",
    menuLabel: "Long Nonpurchase",
    description: "Report view for long nonpurchase trends.",
    sectionKey: "data-report",
    readEndpoint: "/API/PrepayReport/LongNonpurchaseSituation",
    readOperationKind: "report-read",
    filters: [
      filterField("customerId", "Customer Id", "Customer id"),
      filterField("meterId", "Meter Id", "Meter id"),
      filterField("nonpurchaseDaysStart", "Nonpurchase Days Start", "Start days", "number"),
      filterField("nonpurchaseDaysEnd", "Nonpurchase Days End", "End days", "number"),
    ],
    columns: [
      { key: "customerId", label: "Customer Id" },
      { key: "customerName", label: "Customer Name" },
      { key: "meterId", label: "Meter Id" },
      { key: "tariff", label: "Tariff" },
    ],
  },
  {
    kind: "data",
    path: "/data-report/low-purchase",
    title: "Low Purchase Situation",
    menuLabel: "Low Purchase",
    description: "Report view for low purchase accounts and balances.",
    sectionKey: "data-report",
    readEndpoint: "/API/PrepayReport/LowPurchaseSituation",
    readOperationKind: "report-read",
    requiredReadFilters: ["fromDate", "toDate"],
    omitReadPaging: true,
    requestDateFormat: "day-first",
    filters: [
      filterField("customerId", "Customer Id", "Customer id"),
      filterField("meterId", "Meter Id", "Meter id"),
      ...dateRangeFilters,
      filterField("lowLimit", "Low Limit", "Low balance threshold", "number"),
    ],
    columns: [
      { key: "customerId", label: "Customer Id" },
      { key: "customerName", label: "Customer Name" },
      { key: "meterId", label: "Meter Id" },
      { key: "tariffId", label: "Tariff Id" },
      { key: "totalUnit", label: "Total Unit", align: "end" },
      { key: "totalPaid", label: "Total Paid", align: "end" },
      { key: "customerAddress", label: "Customer Address" },
    ],
  },
  {
    kind: "data",
    path: "/data-report/consumption-statistics",
    title: "Consumption Statistics",
    menuLabel: "Consumption Statistics",
    description: "Report view for aggregated consumption performance.",
    sectionKey: "data-report",
    readEndpoint: "/API/PrepayReport/ConsumptionStatistics",
    readOperationKind: "report-read",
    requiredReadFilters: ["fromDate", "toDate"],
    omitReadPaging: true,
    requestDateFormat: "day-first",
    filters: [
      filterField("customerId", "Customer Id", "Customer id"),
      filterField("meterId", "Meter Id", "Meter id"),
      ...dateRangeFilters,
    ],
    columns: [
      { key: "collectionDate", label: "Collection Date" },
      { key: "consumption", label: "Consumption", align: "end" },
    ],
  },
  {
    kind: "site-consumption",
    path: "/site-consumption",
    title: "Site Consumption",
    menuLabel: "Site Consumption",
    description: "Dedicated snapshot view for site-level consumption totals and trends.",
    sectionKey: "data-report",
  },
  {
    kind: "data",
    path: "/data-report/interval-data",
    title: "Interval Data",
    menuLabel: "Interval Data",
    description: "Interval report with meter drill-down action for hourly views.",
    sectionKey: "data-report",
    readEndpoint: "/api/DailyDataMeter/read",
    readOperationKind: "report-read",
    filters: [searchFilter],
    columns: intervalColumns,
    rowActions: [
      {
        key: "hourly",
        label: "Hourly",
        endpoint: "/api/DailyDataMeter/readHourly",
        tone: "primary",
        operationKind: "generic",
      },
    ],
    toolbarActions: [
      {
        key: "monthly",
        label: "Monthly View",
        endpoint: "/api/DailyDataMeter/readMonthly",
        tone: "neutral",
        operationKind: "generic",
      },
      {
        key: "readmore",
        label: "Read More",
        endpoint: "/api/DailyDataMeter/readMore",
        tone: "neutral",
        operationKind: "generic",
      },
    ],
  },
  {
    kind: "data",
    path: "/load-profile/electric-energy",
    title: "Electric Energy Curve",
    menuLabel: "Electric Energy Curve",
    description: "Time-series load profile for electric energy consumption curves.",
    sectionKey: "load-profile",
    readEndpoint: "/API/LoadProfile/ElectricEnergyCurve",
    readOperationKind: "report-read",
    filters: [searchFilter, ...dateRangeFilters],
    columns: loadProfileColumns,
    toolbarActions: [createClientExportAction("/API/LoadProfile/ElectricEnergyCurve")],
  },
  {
    kind: "data",
    path: "/load-profile/instantaneous-value",
    title: "Instantaneous Value Curve",
    menuLabel: "Instantaneous Value",
    description: "Time-series load profile for instantaneous value curves.",
    sectionKey: "load-profile",
    readEndpoint: "/API/LoadProfile/InstantaneousValueCurve",
    readOperationKind: "report-read",
    filters: [searchFilter, ...dateRangeFilters],
    columns: loadProfileColumns,
    toolbarActions: [createClientExportAction("/API/LoadProfile/InstantaneousValueCurve")],
  },
  {
    kind: "data",
    path: "/load-profile/daily-data",
    title: "Daily Data",
    menuLabel: "Daily Data",
    description: "Load profile daily data aggregation.",
    sectionKey: "load-profile",
    readEndpoint: "/API/LoadProfile/DailyData",
    readOperationKind: "report-read",
    filters: [searchFilter, ...dateRangeFilters],
    columns: loadProfileColumns,
    toolbarActions: [createClientExportAction("/API/LoadProfile/DailyData")],
  },
  {
    kind: "data",
    path: "/load-profile/monthly-data",
    title: "Monthly Data",
    menuLabel: "Monthly Data",
    description: "Load profile monthly data aggregation.",
    sectionKey: "load-profile",
    readEndpoint: "/API/LoadProfile/MonthlyData",
    readOperationKind: "report-read",
    filters: [searchFilter, ...dateRangeFilters],
    columns: loadProfileColumns,
    toolbarActions: [createClientExportAction("/API/LoadProfile/MonthlyData")],
  },
];
