import type { AppPageConfig } from "../types/index.ts";
import {
  createClientExportAction,
  dateRangeFilters,
  eventNotificationColumns,
  eventNotificationFilters,
  filterField,
  intervalColumns,
  loadProfileFilters,
  loadProfileColumns,
  searchFilter,
  theftCaseColumns,
  theftSignalColumns,
} from "./page-catalog-shared.ts";

export const reportPages: AppPageConfig[] = [
  {
    kind: "data",
    path: "/data-report/long-nonpurchase",
    title: "Long Nonpurchase Situation",
    menuLabel: "Long Nonpurchase",
    description: "Report view for long nonpurchase trends.",
    sectionKey: "prepay-report",
    aliasPaths: ["/prepay-report/long-nonpurchase-situation"],
    readEndpoint: "/api/reports/non-purchase",
    readMethod: "GET",
    readOperationKind: "report-read",
    filters: [
      filterField("customerId", "Customer Id", "Customer id"),
      filterField("meterId", "Meter Id", "Meter id"),
      ...dateRangeFilters,
      filterField("nonpurchaseDaysStart", "Nonpurchase Days Start", "Start days", "number"),
      filterField("nonpurchaseDaysEnd", "Nonpurchase Days End", "End days", "number"),
    ],
    columns: [
      { key: "customerId", label: "Customer Id" },
      { key: "customerName", label: "Customer Name" },
      { key: "meterId", label: "Meter Id" },
      { key: "tariff", label: "Tariff" },
    ],
    live: { enabled: true, intervalMs: 25_000, pauseOnHidden: true },
    riskIntegration: {
      canOpenCase: true,
      riskSignals: ["long-nonpurchase", "bypass-risk"],
    },
  },
  {
    kind: "data",
    path: "/data-report/low-purchase",
    title: "Low Purchase Situation",
    menuLabel: "Low Purchase",
    description: "Report view for low purchase accounts and balances.",
    sectionKey: "prepay-report",
    aliasPaths: ["/prepay-report/low-purchase-situation"],
    readEndpoint: "/api/reports/low-purchase",
    readMethod: "GET",
    readOperationKind: "report-read",
    requiredReadFilters: ["fromDate", "toDate"],
    omitReadPaging: true,
    requestDateFormat: "day-first",
    filters: [
      filterField("customerId", "Customer Id", "Customer id"),
      filterField("meterId", "Meter Id", "Meter id"),
      ...dateRangeFilters,
      filterField("lowLimit", "Low Limit", "Low balance threshold", "number"),
    ],
    columns: [
      { key: "customerId", label: "Customer Id", searchable: true },
      { key: "customerName", label: "Customer Name", searchable: true },
      { key: "meterId", label: "Meter Id", searchable: true },
      { key: "tariff", label: "Tariff", searchable: true },
      { key: "totalUnit", label: "Total Unit", align: "end" },
      { key: "totalPaid", label: "Total Paid", align: "end" },
      { key: "remainingBalance", label: "Remaining Balance", align: "end" },
      { key: "customerAddress", label: "Customer Address", searchable: true },
    ],
    live: { enabled: true, intervalMs: 20_000, pauseOnHidden: true },
    riskIntegration: {
      canOpenCase: true,
      riskSignals: ["low-purchase", "consumption-drift"],
    },
  },
  {
    kind: "data",
    path: "/data-report/site-consumption",
    title: "Site Consumption",
    menuLabel: "Site Consumption",
    description: "Analytics-first report for site-level consumption totals, trends, and exportable period rows.",
    sectionKey: "prepay-report",
    includeInNavigation: false,
    readEndpoint: "/api/site-consumption/report",
    readOperationKind: "report-read",
    reportDisplayMode: "analytics",
    reportAnalyticsKey: "site-consumption",
    omitReadPaging: true,
    requestDateFormat: "day-first",
    filters: [
      ...dateRangeFilters,
      filterField("granularity", "Granularity", "daily"),
      filterField("sites", "Sites", "Musha,Ogufa"),
      filterField("compareMode", "Compare Mode", "compare"),
    ],
    columns: [
      { key: "periodLabel", label: "Period" },
      { key: "site", label: "Site" },
      { key: "consumption", label: "Consumption", align: "end" },
      { key: "unitLabel", label: "Unit" },
    ],
    toolbarActions: [createClientExportAction("/api/site-consumption/report")],
    live: { enabled: true, intervalMs: 30_000, pauseOnHidden: true },
    riskIntegration: {
      canOpenCase: true,
      riskSignals: ["site-anomaly", "consumption-drift"],
    },
  },
  {
    kind: "data",
    path: "/data-report/theft-signals",
    title: "Theft Signals",
    menuLabel: "Theft Signals",
    description: "Live risk detections generated from nonpurchase, balance, and anomaly correlations.",
    sectionKey: "prepay-report",
    includeInNavigation: false,
    readEndpoint: "/api/theft/signals/read",
    readOperationKind: "table-read",
    filters: [searchFilter],
    columns: theftSignalColumns,
    toolbarActions: [createClientExportAction("/api/theft/signals/read")],
    rowActions: [
      {
        key: "open-case",
        label: "Open Case",
        endpoint: "/api/theft/cases/create",
        tone: "danger",
        operationKind: "theft-case-create",
        fields: [
          {
            key: "notes",
            label: "Notes",
            type: "textarea",
            placeholder: "Add investigation notes",
          },
        ],
      },
    ],
    live: { enabled: true, intervalMs: 10_000, pauseOnHidden: true, critical: true },
    requiredRole: "admin",
    riskIntegration: {
      canOpenCase: true,
      riskSignals: ["theft-signal", "case-intake"],
    },
  },
  {
    kind: "data",
    path: "/data-report/theft-cases",
    title: "Theft Cases",
    menuLabel: "Theft Cases",
    description: "Investigation workspace for active bypass and theft cases.",
    sectionKey: "prepay-report",
    includeInNavigation: false,
    readEndpoint: "/api/theft/cases/read",
    readOperationKind: "table-read",
    filters: [searchFilter],
    columns: theftCaseColumns,
    toolbarActions: [createClientExportAction("/api/theft/cases/read")],
    rowActions: [
      {
        key: "update-case",
        label: "Update Case",
        endpoint: "/api/theft/cases/update",
        tone: "primary",
        operationKind: "generic",
        fields: [
          {
            key: "status",
            label: "Status",
            type: "select",
            placeholder: "Select status",
            options: [
              { label: "New", value: "new" },
              { label: "Active", value: "active" },
              { label: "Investigating", value: "investigating" },
              { label: "Confirmed Theft", value: "confirmed-theft" },
              { label: "False Positive", value: "false-positive" },
              { label: "Closed", value: "closed" },
            ],
          },
          {
            key: "owner",
            label: "Owner",
            type: "text",
            placeholder: "Assign owner",
          },
          {
            key: "notes",
            label: "Notes",
            type: "textarea",
            placeholder: "Update investigation notes",
          },
        ],
      },
    ],
    live: { enabled: true, intervalMs: 8_000, pauseOnHidden: true, critical: true },
    requiredRole: "admin",
    riskIntegration: {
      canOpenCase: true,
      riskSignals: ["case-management", "investigation"],
    },
  },
  {
    kind: "data",
    path: "/data-report/consumption-statistics",
    title: "Consumption Statistics",
    menuLabel: "Consumption Statistics",
    description: "Reference AMR consumption statistics report backed by the original upstream endpoint.",
    sectionKey: "prepay-report",
    aliasPaths: ["/prepay-report/consumption-statistics"],
    readEndpoint: "/api/reports/consumption",
    readMethod: "GET",
    readOperationKind: "report-read",
    reportDisplayMode: "analytics",
    reportAnalyticsKey: "consumption-statistics",
    requiredReadFilters: ["fromDate", "toDate"],
    omitReadPaging: true,
    requestDateFormat: "day-first",
    filters: [
      filterField("customerId", "Customer Id", "Customer id"),
      filterField("meterId", "Meter Id", "Meter id"),
      ...dateRangeFilters,
    ],
    columns: [
      { key: "periodLabel", label: "Period" },
      { key: "customerId", label: "Customer Id" },
      { key: "customerName", label: "Customer Name" },
      { key: "meterId", label: "Meter Id" },
      { key: "consumption", label: "Consumption", align: "end" },
      { key: "totalEnergy", label: "Total Energy", align: "end" },
    ],
    live: { enabled: true, intervalMs: 25_000, pauseOnHidden: true },
    riskIntegration: {
      canOpenCase: true,
      riskSignals: ["consumption-anomaly", "meter-risk"],
    },
  },
  {
    kind: "data",
    path: "/data-report/interval-data",
    title: "Interval Data",
    menuLabel: "Daily Data Meter",
    description: "Interval report with meter drill-down action for hourly views.",
    sectionKey: "prepay-report",
    aliasPaths: [
      "/prepay-report/daily-data",
      "/prepay-report/daily-data-meter",
      "/prepay-report/monthly-data",
    ],
    readEndpoint: "/api/DailyDataMeter/read",
    readOperationKind: "report-read",
    filters: [searchFilter],
    columns: intervalColumns,
    rowActions: [
      {
        key: "hourly",
        label: "Hourly",
        endpoint: "/api/DailyDataMeter/readHourly",
        tone: "primary",
        operationKind: "drilldown",
      },
      {
        key: "monthly",
        label: "Monthly View",
        endpoint: "/api/DailyDataMeter/readMonthly",
        tone: "neutral",
        operationKind: "drilldown",
      },
      {
        key: "readmore",
        label: "Read More",
        endpoint: "/api/DailyDataMeter/readMore",
        tone: "neutral",
        operationKind: "drilldown",
      },
    ],
    live: { enabled: true, intervalMs: 15_000, pauseOnHidden: true },
    riskIntegration: { canOpenCase: true, riskSignals: ["interval-anomaly", "relay-risk"] },
  },
  {
    kind: "data",
    path: "/load-profile/electric-energy",
    title: "Electric Energy Curve",
    menuLabel: "Electric Energy Curve",
    description: "Reference AMR electric energy curve report.",
    sectionKey: "remote-report",
    aliasPaths: [
      "/remote-report/electric-energy-curve",
      "/remote-report/electric-energy-curve-Three",
      "/remote-report/electric-energy-curve-CT",
    ],
    readEndpoint: "/API/LoadProfile/ElectricEnergyCurve",
    readOperationKind: "report-read",
    filters: loadProfileFilters,
    columns: loadProfileColumns,
    toolbarActions: [createClientExportAction("/API/LoadProfile/ElectricEnergyCurve")],
    live: { enabled: true, intervalMs: 20_000, pauseOnHidden: true },
    riskIntegration: { canOpenCase: true, riskSignals: ["load-shape-anomaly"] },
  },
  {
    kind: "data",
    path: "/load-profile/instantaneous-value",
    title: "Instantaneous Value Curve",
    menuLabel: "Instantaneous Value",
    description: "Reference AMR instantaneous value curve report.",
    sectionKey: "remote-report",
    aliasPaths: [
      "/remote-report/instantaneous-value-curve",
      "/remote-report/instantaneous-value-curve-Three",
      "/remote-report/instantaneous-value-curve-CT",
    ],
    readEndpoint: "/API/LoadProfile/InstantaneousValueCurve",
    readOperationKind: "report-read",
    filters: loadProfileFilters,
    columns: loadProfileColumns,
    toolbarActions: [createClientExportAction("/API/LoadProfile/InstantaneousValueCurve")],
    live: { enabled: true, intervalMs: 20_000, pauseOnHidden: true },
    riskIntegration: { canOpenCase: true, riskSignals: ["instantaneous-anomaly"] },
  },
  {
    kind: "data",
    path: "/load-profile/daily-data",
    title: "Daily Data",
    menuLabel: "Daily Data",
    description: "Reference AMR load profile daily data report.",
    sectionKey: "remote-report",
    aliasPaths: [
      "/remote-report/daily-data",
      "/remote-report/daily-data-Three",
      "/remote-report/daily-data-CT",
    ],
    readEndpoint: "/api/reports/daily-amr",
    readMethod: "GET",
    readOperationKind: "report-read",
    filters: loadProfileFilters,
    columns: loadProfileColumns,
    meterDrilldown: {
      primaryEndpoint: "/API/LoadProfile/DailyData",
      fallbackEndpoint: "/api/DailyDataMeter/readHourly",
      refreshMs: 30_000,
    },
    toolbarActions: [createClientExportAction("/api/reports/daily-amr")],
    live: { enabled: true, intervalMs: 15_000, pauseOnHidden: true },
    riskIntegration: { canOpenCase: true, riskSignals: ["daily-load-drift"] },
  },
  {
    kind: "data",
    path: "/load-profile/monthly-data",
    title: "Monthly Data",
    menuLabel: "Monthly Data",
    description: "Reference AMR load profile monthly data report.",
    sectionKey: "remote-report",
    aliasPaths: [
      "/remote-report/monthly-data",
      "/remote-report/monthly-data-Three",
      "/remote-report/monthly-data-CT",
    ],
    readEndpoint: "/api/reports/monthly-amr",
    readMethod: "GET",
    readOperationKind: "report-read",
    filters: loadProfileFilters,
    columns: loadProfileColumns,
    meterDrilldown: {
      primaryEndpoint: "/API/LoadProfile/MonthlyData",
      fallbackEndpoint: "/api/DailyDataMeter/readMonthly",
      refreshMs: 30_000,
    },
    toolbarActions: [createClientExportAction("/api/reports/monthly-amr")],
    live: { enabled: true, intervalMs: 20_000, pauseOnHidden: true },
    riskIntegration: { canOpenCase: true, riskSignals: ["monthly-load-drift"] },
  },
  {
    kind: "data",
    path: "/event/event-notification",
    title: "Event Notification",
    menuLabel: "Event Notification",
    description: "Reference AMR event notification feed.",
    sectionKey: "remote-report",
    aliasPaths: ["/remote-report/event-notification"],
    readEndpoint: "/API/EventNotification/Read",
    readOperationKind: "report-read",
    filters: eventNotificationFilters,
    columns: eventNotificationColumns,
    toolbarActions: [createClientExportAction("/API/EventNotification/Read")],
    live: { enabled: true, intervalMs: 12_000, pauseOnHidden: true, critical: true },
    riskIntegration: { canOpenCase: true, riskSignals: ["event-anomaly", "meter-risk"] },
  },
  {
    kind: "data",
    path: "/remote-report/gprs-online-status",
    title: "GPRS Online Status",
    menuLabel: "GPRS Online Status",
    description: "Live GPRS online status report from the reference AMR workspace.",
    sectionKey: "remote-report",
    readEndpoint: "/API/RemoteReport/GPRSOnlineStatus",
    readOperationKind: "report-read",
    filters: loadProfileFilters,
    columns: loadProfileColumns,
    toolbarActions: [createClientExportAction("/API/RemoteReport/GPRSOnlineStatus")],
    live: { enabled: true, intervalMs: 20_000, pauseOnHidden: true },
    riskIntegration: { canOpenCase: true, riskSignals: ["gprs-status", "communication-risk"] },
  },
];
