import type { AppPageConfig } from "../types/index.ts";
import {
  changeMeterKeyRecordColumns,
  clearTokenRecordColumns,
  createTokenGeneratePage,
  createTokenRecordPage,
  creditTokenRecordColumns,
  maximumPowerRecordColumns,
  meterTestTokenColumns,
  overdraftRecordColumns,
} from "./page-catalog-shared.ts";

export const tokenPages: AppPageConfig[] = [
  createTokenGeneratePage(
    "/token-generate/credit-token",
    "Credit Token",
    "Credit Token",
    "/api/token/creditToken/generate",
    { actionLabel: "Recharge", showQuota: true },
  ),
  createTokenGeneratePage(
    "/token-generate/clear-tamper-token",
    "Clear Tamper Token",
    "Clear Tamper Token",
    "/api/token/clearTamperToken/generate",
    { actionLabel: "Generate Token", showQuota: false },
  ),
  createTokenGeneratePage(
    "/token-generate/clear-credit-token",
    "Clear Credit Token",
    "Clear Credit Token",
    "/api/token/clearCreditToken/generate",
    { actionLabel: "Generate Token", showQuota: false },
  ),
  createTokenGeneratePage(
    "/token-generate/set-max-power-limit-token",
    "Set Maximum Power Limit Token",
    "Set Maximum Power Limit",
    "/api/token/setMaximumPowerLimitToken/generate",
    { actionLabel: "Generate Token", showQuota: false },
  ),
  createTokenGeneratePage(
    "/token-generate/phase-unbalance-token",
    "Phase Power Unbalance Limit",
    "Phase Unbalance Limit",
    "/api/token/setMaximumPhasePowerUnbalanceLimitToken/generate",
    { actionLabel: "Generate Token", showQuota: false },
  ),
  createTokenGeneratePage(
    "/token-generate/change-meter-key-token",
    "Change Meter Key Token",
    "Change Meter Key",
    "/api/token/changeMeterKeyToken/generate",
    { actionLabel: "Generate Token", showQuota: false },
  ),
  createTokenGeneratePage(
    "/token-generate/max-overdraft-token",
    "Max Overdraft Limit Token",
    "Max Overdraft Limit",
    "/api/token/setMaximumOverdraftLimitToken/generate",
    { actionLabel: "Generate Token", showQuota: false },
  ),
  createTokenRecordPage(
    "/token-record/credit-token-record",
    "Credit Token Record",
    "Credit Token Record",
    "/api/token/creditTokenRecord/read",
    {
      columns: creditTokenRecordColumns,
      rowActions: [
        {
          key: "cancel",
          label: "Cancel",
          endpoint: "/api/token/creditTokenRecord/cancel",
          tone: "danger",
          operationKind: "record-cancel",
          confirmMessage: "Cancel this record?",
        },
      ],
    },
  ),
  createTokenRecordPage(
    "/token-record/credit-cancel-record",
    "Credit Cancel Record",
    "Credit Cancel Record",
    "/api/token/creditTokenCancelRecord/read",
    { columns: creditTokenRecordColumns },
  ),
  createTokenRecordPage(
    "/token-record/clear-tamper-record",
    "Clear Tamper Record",
    "Clear Tamper Record",
    "/api/token/clearTamperTokenRecord/read",
    { columns: clearTokenRecordColumns },
  ),
  createTokenRecordPage(
    "/token-record/clear-credit-record",
    "Clear Credit Record",
    "Clear Credit Record",
    "/api/token/clearCreditTokenRecord/read",
    { columns: clearTokenRecordColumns },
  ),
  createTokenRecordPage(
    "/token-record/set-max-power-limit-record",
    "Set Maximum Power Limit Record",
    "Set Maximum Power Record",
    "/api/token/setMaximumPowerLimitTokenRecord/read",
    { columns: maximumPowerRecordColumns },
  ),
  createTokenRecordPage(
    "/token-record/phase-unbalance-record",
    "Phase Power Unbalance Record",
    "Phase Unbalance Record",
    "/api/token/setMaximumPhasePowerUnbalanceLimitTokenRecord/read",
    { columns: maximumPowerRecordColumns },
  ),
  createTokenRecordPage(
    "/token-record/meter-test-token",
    "Meter Test Token",
    "Meter Test Token",
    "/api/token/meterTestToken/read",
    { columns: meterTestTokenColumns },
  ),
  createTokenRecordPage(
    "/token-record/change-meter-key-record",
    "Change Meter Key Record",
    "Change Key Record",
    "/api/token/changeMeterKeyTokenRecord/read",
    { columns: changeMeterKeyRecordColumns },
  ),
  createTokenRecordPage(
    "/token-record/max-overdraft-record",
    "Max Overdraft Limit Record",
    "Max Overdraft Record",
    "/api/token/setMaximumOverdraftLimitTokenRecord/read",
    { columns: overdraftRecordColumns },
  ),
];
