import type { AppPageConfig } from "../types/index.ts";
import {
  changeMeterKeyRecordColumns,
  clearTokenRecordColumns,
  createTokenGeneratePage,
  createTokenRecordPage,
  creditTokenRecordFilters,
  creditTokenRecordColumns,
  maximumOverdraftRecordColumns,
  maximumPhaseUnbalanceRecordColumns,
  maximumPowerRecordColumns,
  meterTestTokenRecordColumns,
  tokenAuditFilters,
} from "./page-catalog-shared.ts";

export const tokenPages: AppPageConfig[] = [
  createTokenGeneratePage(
    "/token-generate/credit-token",
    "Credit Token",
    "Credit Token",
    "/api/token/creditToken/generate",
    {
      actionLabel: "Recharge",
      showQuota: true,
      operationKind: "token-generate-credit",
      successRedirectPath: "/token-record/credit-token-record",
    },
  ),
  createTokenGeneratePage(
    "/token-generate/clear-tamper-token",
    "Clear Tamper Token",
    "Clear Tamper Token",
    "/api/token/clearTamperToken/generate",
    {
      actionLabel: "Generate Token",
      showQuota: false,
      operationKind: "token-generate-basic",
      successRedirectPath: "/token-record/clear-tamper-token-record",
    },
  ),
  createTokenGeneratePage(
    "/token-generate/clear-credit-token",
    "Clear Credit Token",
    "Clear Credit Token",
    "/api/token/clearCreditToken/generate",
    {
      actionLabel: "Generate Token",
      showQuota: false,
      operationKind: "token-generate-basic",
      successRedirectPath: "/token-record/clear-credit-record",
    },
  ),
  createTokenGeneratePage(
    "/token-generate/set-max-power-limit-token",
    "Set Maximum Power Limit Token",
    "Set Maximum Power Limit Token",
    "/api/token/setMaximumPowerLimitToken/generate",
    {
      actionLabel: "Generate Token",
      showQuota: false,
      operationKind: "token-generate-limit",
      successRedirectPath: "/token-record/set-maximum-power-limit-token-record",
    },
  ),
  createTokenGeneratePage(
    "/token-generate/set-maximum-phase-power-unbalance-limit-token",
    "Set Maximum Phase Power Unbalance Limit Token",
    "Set Maximum Phase Power Unbalance Limit Token",
    "/api/token/setMaximumPhasePowerUnbalanceLimitToken/generate",
    {
      actionLabel: "Generate Token",
      showQuota: false,
      operationKind: "token-generate-limit",
      successRedirectPath: "/token-record/set-maximum-phase-power-unbalance-limit-token-record",
    },
  ),
  createTokenGeneratePage(
    "/token-generate/change-meter-key-token",
    "Change Meter Key Token",
    "Change Meter Key Token",
    "/api/token/changeMeterKeyToken/generate",
    {
      actionLabel: "Generate Token",
      showQuota: false,
      operationKind: "token-generate-basic",
      successRedirectPath: "/token-record/change-meter-key-token-record",
    },
  ),
  createTokenGeneratePage(
    "/token-generate/set-maximum-overdraft-limit-token",
    "Set Maximum Overdraft Limit Token",
    "Set Maximum Overdraft Limit Token",
    "/api/token/setMaximumOverdraftLimitToken/generate",
    {
      actionLabel: "Generate Token",
      showQuota: false,
      operationKind: "token-generate-limit",
      successRedirectPath: "/token-record/set-maximum-overdraft-limit-token-record",
    },
  ),
  createTokenGeneratePage(
    "/token-generate/update-meter-key",
    "Update Meter Key",
    "Update Meter Key",
    "/api/token/meterKey/update",
    {
      actionLabel: "Update Key",
      showQuota: false,
      operationKind: "token-generate-basic",
    },
  ),
  createTokenRecordPage(
    "/token-record/credit-token-record",
    "Credit Token Record",
    "Credit Token Record",
    "/api/token/creditTokenRecord/read",
    {
      columns: creditTokenRecordColumns,
      filters: creditTokenRecordFilters,
      rowActions: [
        {
          key: "cancel",
          label: "Cancel",
          endpoint: "/api/token/creditTokenRecord/cancel",
          tone: "danger",
          operationKind: "record-cancel",
          confirmMessage: "Cancel this record?",
        },
      ],
    },
  ),
  createTokenRecordPage(
    "/token-record/credit-token-cancel-record",
    "Credit Token Cancel Record",
    "Credit Token Cancel Record",
    "/api/token/creditTokenCancelRecord/read",
    { columns: creditTokenRecordColumns, filters: creditTokenRecordFilters },
  ),
  createTokenRecordPage(
    "/token-record/clear-tamper-token-record",
    "Clear Tamper Token Record",
    "Clear Tamper Token Record",
    "/api/token/clearTamperTokenRecord/read",
    { columns: clearTokenRecordColumns, filters: tokenAuditFilters },
  ),
  createTokenRecordPage(
    "/token-record/clear-credit-record",
    "Clear Credit Token Record",
    "Clear Credit Token Record",
    "/api/token/clearCreditTokenRecord/read",
    { columns: clearTokenRecordColumns, filters: tokenAuditFilters },
  ),
  createTokenRecordPage(
    "/token-record/set-maximum-power-limit-token-record",
    "Set Maximum Power Limit Token Record",
    "Set Maximum Power Limit Token Record",
    "/api/token/setMaximumPowerLimitTokenRecord/read",
    { columns: maximumPowerRecordColumns, filters: tokenAuditFilters },
  ),
  createTokenRecordPage(
    "/token-record/set-maximum-phase-power-unbalance-limit-token-record",
    "Set Maximum Phase Power Unbalance Limit Token Record",
    "Set Maximum Phase Power Unbalance Limit Token Record",
    "/api/token/setMaximumPhasePowerUnbalanceLimitTokenRecord/read",
    { columns: maximumPhaseUnbalanceRecordColumns, filters: tokenAuditFilters },
  ),
  createTokenRecordPage(
    "/token-record/meter-test-token",
    "Meter Test Token",
    "Meter Test Token",
    "/api/token/meterTestToken/read",
    { columns: meterTestTokenRecordColumns, filters: tokenAuditFilters },
  ),
  createTokenRecordPage(
    "/token-record/change-meter-key-token-record",
    "Change Meter Key Token Record",
    "Change Meter Key Token Record",
    "/api/token/changeMeterKeyTokenRecord/read",
    { columns: changeMeterKeyRecordColumns, filters: tokenAuditFilters },
  ),
  createTokenRecordPage(
    "/token-record/set-maximum-overdraft-limit-token-record",
    "Set Maximum Overdraft Limit Token Record",
    "Set Maximum Overdraft Limit Token Record",
    "/api/token/setMaximumOverdraftLimitTokenRecord/read",
    { columns: maximumOverdraftRecordColumns, filters: tokenAuditFilters },
  ),
];
