import type { AppPageConfig } from "../types/index.ts";

const vendorBase = {
  kind: "vendor",
  requiredRole: "vendor",
  workspace: "vendor",
} as const;

export const vendorPages: AppPageConfig[] = [
  {
    ...vendorBase,
    path: "/vendor/dashboard",
    title: "Vendor Dashboard",
    menuLabel: "Dashboard",
    description: "Wallet balance, reserved funds, and recent vending activity.",
    sectionKey: "vendor-dashboard",
    vendorView: "dashboard",
  },
  {
    ...vendorBase,
    path: "/vendor/buy",
    title: "Buy Units",
    menuLabel: "Buy Units",
    description: "Search a site-scoped meter, choose delivery mode, and prepare the debit.",
    sectionKey: "vendor-buy",
    vendorView: "buy",
  },
  {
    ...vendorBase,
    path: "/vendor/buy/confirm",
    title: "Confirm Purchase",
    menuLabel: "Confirm Purchase",
    description: "Review the meter, amount, and delivery method before debiting the wallet.",
    sectionKey: "vendor-buy",
    includeInNavigation: false,
    navigationPath: "/vendor/buy",
    tabPath: "/vendor/buy",
    vendorView: "buy-confirm",
  },
  {
    ...vendorBase,
    path: "/vendor/buy/receipt/:receiptId",
    title: "Purchase Receipt",
    menuLabel: "Purchase Receipt",
    description: "Review and print the completed vending receipt.",
    sectionKey: "vendor-buy",
    includeInNavigation: false,
    navigationPath: "/vendor/buy",
    tabPath: "/vendor/buy",
    vendorView: "buy-receipt",
  },
  {
    ...vendorBase,
    path: "/vendor/transactions",
    title: "Transactions",
    menuLabel: "Transactions",
    description: "Track purchase, funding, reversal, and commission activity with filters.",
    sectionKey: "vendor-history",
    vendorView: "transactions",
  },
  {
    ...vendorBase,
    path: "/vendor/receipts",
    title: "Receipts",
    menuLabel: "Receipts",
    description: "Browse and retrieve remote-send and token-generation receipts.",
    sectionKey: "vendor-history",
    vendorView: "receipts",
  },
  {
    ...vendorBase,
    path: "/vendor/commission",
    title: "Commission",
    menuLabel: "Commission",
    description: "Review accrued commission, settlements, and historical commission movements.",
    sectionKey: "vendor-wallet",
    vendorView: "commission",
  },
  {
    ...vendorBase,
    path: "/vendor/topup",
    title: "Request Top-Up",
    menuLabel: "Top-Up",
    description: "Initiate wallet funding, attach proof, and submit for finance review.",
    sectionKey: "vendor-wallet",
    vendorView: "topup",
  },
  {
    ...vendorBase,
    path: "/vendor/topup/:requestId",
    title: "Funding Tracker",
    menuLabel: "Funding Tracker",
    description: "Track a funding request from initiation through posting.",
    sectionKey: "vendor-wallet",
    includeInNavigation: false,
    navigationPath: "/vendor/topup",
    tabPath: "/vendor/topup",
    vendorView: "topup-status",
  },
  {
    ...vendorBase,
    path: "/vendor/statement",
    title: "Statement",
    menuLabel: "Statement",
    description: "Review debits and credits across a selected statement range.",
    sectionKey: "vendor-wallet",
    vendorView: "statement",
  },
  {
    ...vendorBase,
    path: "/vendor/profile",
    title: "Profile",
    menuLabel: "Profile",
    description: "Read-only vendor account and wallet assignment details.",
    sectionKey: "vendor-account",
    vendorView: "profile",
  },
];
