import type { AppPageConfig } from "../types/index.ts";
import { createClientExportAction, searchFilter } from "./page-catalog-shared.ts";

const walletAdminBase = {
  workspace: "wallet-admin",
  requiredRole: "finance,admin,ops_manager",
} as const;

export const walletAdminPages: AppPageConfig[] = [
  {
    ...walletAdminBase,
    kind: "wallet-admin-home",
    path: "/wallet-admin/overview",
    title: "Wallet Command",
    menuLabel: "Overview",
    description: "Dedicated control room for vendor onboarding, funding approval, commission, and reconciliation.",
    sectionKey: "wallet-admin-home",
  },
  {
    ...walletAdminBase,
    kind: "data",
    path: "/wallet-admin/vendor-onboarding",
    title: "Vendor Onboarding Queue",
    menuLabel: "Vendor Onboarding",
    description: "Finance approval queue for vendors awaiting onboarding review and wallet provisioning.",
    sectionKey: "wallet-admin-vendors",
    readEndpoint: "/api/vendor/onboarding/queue",
    readMethod: "GET",
    readOperationKind: "table-read",
    filters: [searchFilter],
    columns: [
      { key: "vendorCode", label: "Vendor Code", searchable: true },
      { key: "vendorName", label: "Vendor Name", searchable: true },
      { key: "siteCode", label: "Site" },
      { key: "submittedAt", label: "Submitted At" },
      { key: "kycStatus", label: "KYC Status" },
      { key: "submittedDocumentsCount", label: "Docs", align: "end" },
      { key: "bankStatus", label: "Bank" },
      { key: "approvalStatus", label: "Approval" },
    ],
    rowActions: [
      {
        key: "vendor-onboarding-approve",
        label: "Approve",
        endpoint: "/api/vendor/approval/approve",
        tone: "primary",
        fields: [
          {
            key: "notes",
            label: "Approval Notes",
            type: "textarea",
            placeholder: "Add optional finance notes",
          },
        ],
        confirmMessage: "Approve this vendor and provision the wallet now?",
      },
    ],
    toolbarActions: [createClientExportAction("/api/vendor/onboarding/queue")],
    requiredRole: "finance,admin",
  },
  {
    ...walletAdminBase,
    kind: "data",
    path: "/wallet-admin/funding-pending",
    title: "Funding Approval Queue",
    menuLabel: "Funding Queue",
    description: "Finance queue for posted proofs awaiting wallet funding approval.",
    sectionKey: "wallet-admin-funding",
    readEndpoint: "/api/wallet/funding/pending",
    readMethod: "GET",
    readOperationKind: "table-read",
    filters: [searchFilter],
    columns: [
      { key: "vendorCode", label: "Vendor Code", searchable: true },
      { key: "vendorName", label: "Vendor Name", searchable: true },
      { key: "siteCode", label: "Site" },
      { key: "amount", label: "Amount", align: "end" },
      { key: "channel", label: "Channel" },
      { key: "reference", label: "Reference", searchable: true },
      { key: "proofStatus", label: "Proof" },
      { key: "status", label: "Status" },
    ],
    rowActions: [
      {
        key: "wallet-funding-approve",
        label: "Approve Funding",
        endpoint: "/api/wallet/funding/approve",
        tone: "primary",
        fields: [
          {
            key: "externalBankRef",
            label: "Bank Reference",
            type: "text",
            placeholder: "Enter external bank reference",
            required: true,
          },
          {
            key: "reviewerNote",
            label: "Reviewer Note",
            type: "textarea",
            placeholder: "Add optional approval note",
          },
        ],
        confirmMessage: "Approve this funding request and post the wallet credit now?",
      },
      {
        key: "wallet-funding-reject",
        label: "Reject Funding",
        endpoint: "/api/wallet/funding/reject",
        tone: "danger",
        fields: [
          {
            key: "reason",
            label: "Rejection Reason",
            type: "textarea",
            placeholder: "State the reason for rejecting this funding request",
            required: true,
          },
        ],
        confirmMessage: "Reject this funding request?",
      },
    ],
    toolbarActions: [createClientExportAction("/api/wallet/funding/pending")],
    requiredRole: "finance,admin",
  },
  {
    ...walletAdminBase,
    kind: "data",
    path: "/wallet-admin/wallet-kpis",
    title: "Wallet Finance KPIs",
    menuLabel: "Wallet KPIs",
    description: "Internal float, reserve, failure, commission, and exhaustion risk indicators.",
    sectionKey: "wallet-admin-funding",
    readEndpoint: "/api/wallet/finance/kpis",
    readMethod: "GET",
    readOperationKind: "table-read",
    filters: [],
    columns: [
      { key: "totalVendorFloat", label: "Vendor Float", align: "end" },
      { key: "totalReserved", label: "Reserved", align: "end" },
      { key: "totalUnsettledCommission", label: "Unsettled Commission", align: "end" },
      { key: "failedPurchaseCount", label: "Failed Purchases", align: "end" },
      { key: "walletsNearExhaustion", label: "Near Exhaustion", align: "end" },
      { key: "exhaustionRiskRate", label: "Exhaustion Risk %", align: "end" },
    ],
    toolbarActions: [createClientExportAction("/api/wallet/finance/kpis")],
  },
  {
    ...walletAdminBase,
    kind: "data",
    path: "/wallet-admin/commission-rules",
    title: "Commission Rules",
    menuLabel: "Commission Rules",
    description: "Manage vendor override commission rates with outstanding balances visible.",
    sectionKey: "wallet-admin-funding",
    readEndpoint: "/api/wallet/commission/rules",
    readMethod: "GET",
    readOperationKind: "table-read",
    filters: [searchFilter],
    columns: [
      { key: "vendorCode", label: "Vendor Code", searchable: true },
      { key: "vendorName", label: "Vendor Name", searchable: true },
      { key: "siteCode", label: "Site" },
      { key: "rate", label: "Rate", align: "end" },
      { key: "overrideSource", label: "Source" },
      { key: "totalOutstanding", label: "Outstanding", align: "end" },
      { key: "updatedAt", label: "Updated At" },
    ],
    rowActions: [
      {
        key: "wallet-commission-rule-update",
        label: "Update Rate",
        endpoint: "/api/wallet/commission/rules-update",
        tone: "primary",
        fields: [
          {
            key: "rate",
            label: "Commission Rate",
            type: "number",
            placeholder: "Enter decimal rate, e.g. 0.025",
            required: true,
          },
        ],
        confirmMessage: "Update this vendor commission rate now?",
      },
    ],
    toolbarActions: [createClientExportAction("/api/wallet/commission/rules")],
    requiredRole: "finance,admin",
  },
  {
    ...walletAdminBase,
    kind: "data",
    path: "/wallet-admin/settlement-batches",
    title: "Settlement Batches",
    menuLabel: "Settlement Batches",
    description: "Preview and post daily commission settlement batches.",
    sectionKey: "wallet-admin-settlement",
    readEndpoint: "/api/wallet/settlement/batches",
    readMethod: "GET",
    readOperationKind: "table-read",
    filters: [
      {
        key: "businessDate",
        label: "Business Date",
        placeholder: "Select business date",
        type: "date",
      },
    ],
    columns: [
      { key: "businessDate", label: "Business Date" },
      { key: "status", label: "Status" },
      { key: "totalCommissionCredits", label: "Total Credits", align: "end" },
      { key: "itemCount", label: "Items", align: "end" },
      { key: "createdAt", label: "Created At" },
      { key: "postedAt", label: "Posted At" },
    ],
    toolbarActions: [
      createClientExportAction("/api/wallet/settlement/batches"),
      {
        key: "wallet-settlement-preview",
        label: "Preview Settlement",
        endpoint: "/api/wallet/settlement/preview",
        tone: "neutral",
        operationKind: "management-create",
        fields: [
          {
            key: "businessDate",
            label: "Business Date",
            type: "date",
            placeholder: "Select business date",
          },
        ],
      },
      {
        key: "wallet-settlement-run",
        label: "Run Settlement",
        endpoint: "/api/wallet/settlement/run",
        tone: "primary",
        operationKind: "management-create",
        fields: [
          {
            key: "businessDate",
            label: "Business Date",
            type: "date",
            placeholder: "Select business date",
          },
        ],
        confirmMessage: "Post the commission settlement batch for this business date now?",
      },
    ],
  },
  {
    ...walletAdminBase,
    kind: "data",
    path: "/wallet-admin/reconciliation",
    title: "Reconciliation Summary",
    menuLabel: "Reconciliation",
    description: "Daily wallet reconciliation summary with report-lock status and settlement totals.",
    sectionKey: "wallet-admin-settlement",
    readEndpoint: "/api/reconciliation/summary",
    readMethod: "GET",
    readOperationKind: "table-read",
    filters: [
      {
        key: "businessDate",
        label: "Business Date",
        placeholder: "Select business date",
        type: "date",
      },
    ],
    columns: [
      { key: "businessDate", label: "Business Date" },
      { key: "totalRuns", label: "Runs", align: "end" },
      { key: "totalExceptions", label: "Exceptions", align: "end" },
      { key: "openExceptions", label: "Open", align: "end" },
      { key: "criticalExceptions", label: "Critical", align: "end" },
      { key: "lockedReportCount", label: "Locked Reports", align: "end" },
      { key: "lastRunCompletedAt", label: "Last Completed" },
      { key: "stageSummary", label: "Stage Summary" },
    ],
    toolbarActions: [
      createClientExportAction("/api/reconciliation/summary"),
      {
        key: "wallet-reconciliation-run",
        label: "Run Reconciliation",
        endpoint: "/api/reconciliation/run",
        tone: "primary",
        operationKind: "management-create",
      },
    ],
  },
  {
    ...walletAdminBase,
    kind: "data",
    path: "/wallet-admin/exceptions",
    title: "Exception Board",
    menuLabel: "Exceptions",
    description: "Operational board for reconciliation exceptions, SLA escalation, and coded resolution.",
    sectionKey: "wallet-admin-settlement",
    readEndpoint: "/api/reconciliation/exceptions",
    readMethod: "GET",
    readOperationKind: "table-read",
    filters: [
      searchFilter,
      {
        key: "severity",
        label: "Severity",
        placeholder: "Filter severity",
        type: "text",
      },
      {
        key: "status",
        label: "Status",
        placeholder: "Filter status",
        type: "text",
      },
    ],
    columns: [
      { key: "type", label: "Type", searchable: true },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
      { key: "siteCode", label: "Site" },
      { key: "summary", label: "Summary", searchable: true },
      { key: "assignee", label: "Assigned To" },
      { key: "dueAt", label: "SLA Due" },
      { key: "detectedAt", label: "Detected At" },
    ],
    rowActions: [
      {
        key: "wallet-exception-assign",
        label: "Assign",
        endpoint: "/api/reconciliation/exceptions/assign",
        tone: "neutral",
        fields: [
          {
            key: "assignee",
            label: "Assign To",
            type: "text",
            placeholder: "Enter assignee username",
            required: true,
          },
        ],
      },
      {
        key: "wallet-exception-escalate",
        label: "Escalate",
        endpoint: "/api/reconciliation/exceptions/escalate",
        tone: "danger",
        fields: [
          {
            key: "reason",
            label: "Escalation Reason",
            type: "textarea",
            placeholder: "State why this exception is being escalated",
            required: true,
          },
        ],
      },
      {
        key: "wallet-exception-resolve",
        label: "Resolve",
        endpoint: "/api/reconciliation/exceptions/resolve",
        tone: "primary",
        fields: [
          {
            key: "resolutionCode",
            label: "Resolution Code",
            type: "text",
            placeholder: "e.g. matched-manually, released-reservation",
            required: true,
          },
          {
            key: "resolutionNotes",
            label: "Resolution Notes",
            type: "textarea",
            placeholder: "Describe the final resolution taken",
            required: true,
          },
        ],
      },
    ],
    toolbarActions: [createClientExportAction("/api/reconciliation/exceptions")],
  },
  {
    ...walletAdminBase,
    kind: "data",
    path: "/wallet-admin/settlement-report",
    title: "Settlement Reports",
    menuLabel: "Settlement Report",
    description: "Latest settlement report with site-level commission and operational totals.",
    sectionKey: "wallet-admin-settlement",
    readEndpoint: "/api/reconciliation/settlement/latest",
    readMethod: "GET",
    readOperationKind: "table-read",
    filters: [],
    columns: [
      { key: "siteCode", label: "Site" },
      { key: "totalFundingPosted", label: "Funding Posted", align: "end" },
      { key: "totalPurchases", label: "Purchases", align: "end" },
      { key: "totalCommissionAccrued", label: "Commission", align: "end" },
      { key: "closingTotalFloat", label: "Closing Float", align: "end" },
      { key: "purchaseCount", label: "Purchases Count", align: "end" },
      { key: "exceptionCount", label: "Exceptions", align: "end" },
    ],
    toolbarActions: [createClientExportAction("/api/reconciliation/settlement/latest")],
  },
];
